// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/MrBns/form-response/internal/app"
	"github.com/MrBns/form-response/internal/config"
	"github.com/MrBns/form-response/internal/handler"
	"github.com/MrBns/form-response/internal/notifier"
)

// Injectors from wire.go:

// initializeApp is the Wire injector function.
// Wire reads this function's body and generates the wiring code in wire_gen.go.
func initializeApp() (*app.App, error) {
	configConfig := config.Load()
	serverConfig := config.ProvideServerConfig(configConfig)
	telegramConfig := config.ProvideTelegramConfig(configConfig)
	telegramNotifier := notifier.ProvideTelegramNotifier(telegramConfig)
	discordConfig := config.ProvideDiscordConfig(configConfig)
	discordNotifier := notifier.ProvideDiscordNotifier(discordConfig)
	notifiers := notifier.ProvideNotifiers(telegramNotifier, discordNotifier)
	formHandler := handler.NewFormHandler(notifiers)
	appApp := app.New(serverConfig, formHandler, notifiers)
	return appApp, nil
}
